apiVersion: v1
kind: Service
metadata:
  name: {{.Values.services.mssvc.name}}
spec:
  type: {{.Values.services.mssvc.type}}
  selector:
    app: {{.Values.services.mssvc.selector.app}}
  ports:
   - port: {{.Values.services.mssvc.ports.port}}
     targetPort: {{.Values.services.mssvc.ports.targetPort}}
     nodePort: {{.Values.services.mssvc.ports.nodePort}}